name: Robot Framework Tests

on:
  schedule:
    - cron: '0 5 * * *' # 05:00 da manhã (UTC)
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar testes Robot
        run: |
          robot -d results tests/

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results
      - name: Enviar E-mail com link do Report
        if: always() # Envia mesmo se o teste falhar
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Relatório de Testes API: ${{ job.status }}"
          to: seu-email-destino@exemplo.com
          from: GitHub Actions Automation
          body: |
            Os testes do Robot Framework terminaram com status: ${{ job.status }}.
            
            Você pode baixar os relatórios e ver os logs no link abaixo:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            (O arquivo está na seção 'Artifacts' no final da página) 
